
export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_BY_ID = 'FETCH_RENTALS_BY_ID';
export const FETCH_RENTALS_BY_ID_SUCESS = 'FETCH_RENTALS_BY_ID_SUCESS';
export const FETCH_RENTALS_BY_ID_INIT = 'FETCH_RENTALS_BY_ID_INIT';